version: '3'

services:
  web:
    build: .
    container_name: web
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web

volumes:
  static_volume:
  postgres_data: